set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'sjbach/lusty'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'majutsushi/tagbar'
Plugin 'kana/vim-textobj-entire'
Plugin 'kana/vim-textobj-line'
Plugin 'kana/vim-textobj-user'
Plugin 'terryma/vim-expand-region'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'kien/ctrlp.vim'

Plugin 'altercation/vim-colors-solarized'

Plugin 'rust-lang/rust.vim'

call vundle#end()
filetype plugin indent on

" Set Theme
colorscheme solarized
set bg=dark

" Don't create annoying files
set nobackup
set noswapfile
 
" Enable color syntaxing
syntax on

" Enable hidden buffer
set hidden

" Add line numbers
set number

" Use 4 spaces to indent
set expandtab
set shiftwidth=4
set softtabstop=4

" Highlight search results
set hlsearch
" Incremental search
set incsearch

set nowrap

set backspace=indent,eol,start

set clipboard=unnamed

" Disable arrows, get used to hjkl
noremap <Left> <NOP>
noremap <Down> <NOP>
noremap <Up> <NOP>
noremap <Right> <NOP>
inoremap <Left> <NOP>
inoremap <Down> <NOP>
inoremap <Up> <NOP>
inoremap <Right> <NOP>

inoremap <Esc> <NOP>
inoremap jk <Esc>
inoremap kj <Esc>

" Disable annoying beeping
set noerrorbells
set vb t_vb=

autocmd BufRead,BufNewFile *.erb set filetype=eruby.html

" NERDTree settings
let NERDTreeIgnore = ['\.pyc$', '^__pycache__$', '\~$', '\.o$', '\.d$']

au BufRead,BufNewFile *.hamlc set ft=haml

"autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2
"autocmd FileType sh setlocal tabstop=2 shiftwidth=2 softtabstop=2
"autocmd FileType jade setlocal tabstop=2 shiftwidth=2 softtabstop=2
"autocmd FileType javascript setlocal tabstop=2 shiftwidth=2 softtabstop=2
"autocmd FileType java setlocal tabstop=4 shiftwidth=4 softtabstop=4

"autocmd FileType go setlocal tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab

set shell=bash

set exrc
set secure

set mouse=nicra
set ttymouse=sgr

let mapleader = "\<Space>"
nnoremap <Leader>w :w<CR>

nmap <Leader><Leader> V
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

let g:expand_region_text_objects = {
      \ 'iw'  :0,
      \ 'iW'  :0,
      \ 'i"'  :0,
      \ 'i''' :0,
      \ 'i]'  :1,
      \ 'i)'  :1,
      \ 'i}'  :1,
      \ 'il'  :0,
      \ 'al'  :0,
      \ 'ip'  :0,
      \ 'ie'  :0,
      \ }

source ~/.vimrc.local
